name: techmarket
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1
  http: ^1.1.2
  yandex_mapkit: ^3.4.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/location_pin.png
